name: absence_manager_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.4
  api:
    path: ./api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  generate: true