name: absence_manager_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  json_serializable: ^6.9.4
  api:
    path: ./api
  mockito: ^5.4.5
  mocktail: ^1.0.4
  bloc_test: ^9.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0-0.0.dev

  
flutter:
  uses-material-design: true
  generate: true